"""empty message

Revision ID: a4f16e15e4ad
Revises: 2f0c927e8407
Create Date: 2024-10-31 15:35:23.068714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a4f16e15e4ad'
down_revision: Union[str, None] = '2f0c927e8407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###  
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('contact_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('contact_title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
        batch_op.alter_column('fax',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('fax',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('contact_title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('contact_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('id')

    op.create_table('suppliers',
    sa.Column('supplier_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('contact_title', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('fax', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('homepage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('supplier_id', name='pk_suppliers'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customer_demographics',
    sa.Column('customer_type_id', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('customer_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_type_id', name='pk_customer_demographics'),
    postgresql_ignore_search_path=False
    )
    op.create_table('products',
    sa.Column('product_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quantity_per_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('units_in_stock', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('units_on_order', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('reorder_level', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('discontinued', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name='fk_products_categories'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name='fk_products_suppliers'),
    sa.PrimaryKeyConstraint('product_id', name='pk_products'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shippers',
    sa.Column('shipper_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('shipper_id', name='pk_shippers'),
    postgresql_ignore_search_path=False
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('title_of_courtesy', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('home_phone', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reports_to', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('photo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reports_to'], ['employees.employee_id'], name='fk_employees_employees'),
    sa.PrimaryKeyConstraint('employee_id', name='pk_employees'),
    postgresql_ignore_search_path=False
    )
    op.create_table('employee_territories',
    sa.Column('employee_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('territory_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_employee_territories_employees'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.territory_id'], name='fk_employee_territories_territories'),
    sa.PrimaryKeyConstraint('employee_id', 'territory_id', name='pk_employee_territories')
    )
    op.create_table('us_states',
    sa.Column('state_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('state_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state_abbr', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('state_region', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('state_id', name='pk_usstates')
    )
    op.create_table('region',
    sa.Column('region_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('region_description', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('region_id', name='pk_region'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customer_customer_demo',
    sa.Column('customer_id', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('customer_type_id', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_customer_customer_demo_customers'),
    sa.ForeignKeyConstraint(['customer_type_id'], ['customer_demographics.customer_type_id'], name='fk_customer_customer_demo_customer_demographics'),
    sa.PrimaryKeyConstraint('customer_id', 'customer_type_id', name='pk_customer_customer_demo')
    )
    op.create_table('territories',
    sa.Column('territory_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('territory_description', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], name='fk_territories_region'),
    sa.PrimaryKeyConstraint('territory_id', name='pk_territories')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('required_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('shipped_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ship_via', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('freight', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('ship_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('ship_address', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('ship_city', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ship_region', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('ship_postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ship_country', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='fk_orders_customers'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_orders_employees'),
    sa.ForeignKeyConstraint(['ship_via'], ['shippers.shipper_id'], name='fk_orders_shippers'),
    sa.PrimaryKeyConstraint('order_id', name='pk_orders'),
    postgresql_ignore_search_path=False
    )
    op.create_table('categories',
    sa.Column('category_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category_id', name='pk_categories'),
    postgresql_ignore_search_path=False
    )
    op.create_table('order_details',
    sa.Column('order_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('discount', sa.REAL(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='fk_order_details_orders'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='fk_order_details_products'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name='pk_order_details')
    )
    # ### end Alembic commands ###
